version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chedli123
      POSTGRES_DB: task_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network

  redis:
    image: redis:7-alpine
    container_name: task-manager-redis
    ports:
      - "6379:6379"
    networks:
      - task-manager-network

  backend:
    build: ./backend
    container_name: task-manager-api
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: postgres              
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: chedli123
      DB_NAME: task_manager_db
      REDIS_URL: redis://redis:6379  
      JWT_SECRET: dev-secret-change-in-production
      CORS_ORIGIN: http://localhost:3000 
    depends_on:
      - postgres
      - redis
    networks:
      - task-manager-network

  frontend:
    build:
      context: ./frontend
    container_name: task-manager-frontend
    ports:
      - "3000:80"
    environment:
        VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - task-manager-network
  

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - task-manager-network
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    privileged: true
    networks:
    - task-manager-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - task-manager-network
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - task-manager-network
    depends_on:
      - prometheus


volumes:
  postgres_data:
  prometheus_data:
  grafana_data:     
networks:
  task-manager-network:
    driver: bridge