---
all:
  children:
    production:
      hosts:
        taskmanager-vm:
          ansible_host: 20.208.34.172
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/azure_taskmanager
          ansible_python_interpreter: /usr/bin/python3

  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
