apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chedli01/task_management_devops.git'
    targetRevision: HEAD
    path: kubernetes/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: task-manager-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: backend
      jsonPointers:
        - /spec/replicas