apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z postgres 5432; do echo waiting for db; sleep 2; done"]
      containers:
      - name: backend
        image: my-registry/backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: task-manager-backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    app: backend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  labels:
    release: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: task-manager-backend
  endpoints:
  - port: http
    path: /api/metrics
    interval: 15s