db_password: "{{ vault_db_password }}"
jwt_secret: "{{ vault_jwt_secret }}"
backend_port: 5000
frontend_port: 3000
domain_name: "{{ ansible_host }}"  # Uses IP for now
storage_account_name: "taskmanagerprodq20xwdk8"
backup_retention_days: 7
docker_hub_username: "{{ vault_docker_hub_username }}"
docker_hub_password: "{{ vault_docker_hub_password }}"
image_tag: "{{ lookup('env','IMAGE_TAG') | default(latest) }}"